cups_lemon_juice = float(input('Enter amount of lemon juice (in cups):\n'))
amount_water = float(input('Enter amount of water (in cups):\n'))
amount_agave_nectar = float(input('Enter amount of agave nectar (in cups):\n'))
servings = float(input('How many servings does this make?\n\n'))
print('Lemonade ingredients - yields', '{:.2f}'.format(servings), 'servings')
print('{.2f}'.format(cups_lemon_juice), 'cup(s) lemon juice')
print('{.2f}'.format(amount_water), 'cup(s) water')
print('{.2f}'.format(amount_agave_nectar), 'cup(s) agave nectar')

servings2 = int(input('How many servings would you like to make?\n\n'))
print('Lemonade ingredients - yields', '{:.2f}'.format(servings2), 'servings')
print('{.2f}'.format(cups_lemon_juice * 8), 'cup(s) lemon juice')
print('{.2f}'.format(amount_water * 8), 'cup(s) water')
print('{.2f}'.format(amount_agave_nectar * 8), 'cup(s) agave nectar')
print('Lemonade ingredients - yields', '{:.2f}'.format(servings2), 'servings')
print('{:.2f}'.format((cups_lemon_juice * 8) / 16), 'gallon(s) lemon juice')
print('{:.2f}'.format((amount_water * 8) / 16), 'gallon(s) water')
print('{:.2f}'.format((amount_agave_nectar * 8) / 16), 'gallon(s) agave nectar')
